data = [
    {"name": "Instagram", "follower_count": 346, "description": "Social media platform"},
    {"name": "Google", "follower_count": 100, "description": "Search engine"},
    {"name": "Twitter", "follower_count": 37, "description": "Social network"},
    {"name": "YouTube", "follower_count": 71, "description": "Video sharing platform"},
    {"name": "Facebook", "follower_count": 214, "description": "Social media platform"},
    {"name": "TikTok", "follower_count": 150, "description": "Short-form video app"},
    {"name": "LinkedIn", "follower_count": 25, "description": "Professional networking platform"},
    {"name": "Netflix", "follower_count": 32, "description": "Streaming service"},
    {"name": "Spotify", "follower_count": 15, "description": "Music streaming platform"},
    {"name": "Snapchat", "follower_count": 20, "description": "Multimedia messaging app"},
    {"name": "Pinterest", "follower_count": 11, "description": "Visual discovery platform"},
    {"name": "Reddit", "follower_count": 8, "description": "Online discussion forum"},
    {"name": "WhatsApp", "follower_count": 96, "description": "Messaging app"},
    {"name": "Amazon", "follower_count": 28, "description": "E-commerce platform"},
    {"name": "Twitch", "follower_count": 15, "description": "Live streaming platform"},
    {"name": "Discord", "follower_count": 6, "description": "Chat and community platform"},
    {"name": "Cristiano Ronaldo", "follower_count": 630, "description": "Footballer"},
    {"name": "Selena Gomez", "follower_count": 429, "description": "Singer and actress"},
    {"name": "Kylie Jenner", "follower_count": 399, "description": "Media personality"},
    {"name": "Dwayne Johnson", "follower_count": 396, "description": "Actor"},
    {"name": "Ariana Grande", "follower_count": 380, "description": "Singer"},
    {"name": "Kim Kardashian", "follower_count": 364, "description": "Media personality"},
    {"name": "Lionel Messi", "follower_count": 500, "description": "Footballer"},
    {"name": "Taylor Swift", "follower_count": 279, "description": "Singer"},
    {"name": "Virat Kohli", "follower_count": 260, "description": "Cricketer"},
]